const money = (value) => String(Math.round(value * 100))

const contract = ({
  id,
  clientId,
  clientName,
  contractName,
  objectName,
  city,
  coordinator,
  revenue,
  labor,
  materials,
  equipment,
  other,
  targetBps,
  plannedHours,
  actualHours,
  completeness,
  status,
  issues = [],
  note,
}) => {
  const hasCompleteCost = [labor, materials, equipment, other].every(Number.isFinite)
  const totalCost = hasCompleteCost ? labor + materials + equipment + other : null
  const margin = totalCost === null ? null : revenue - totalCost
  const profitabilityBps = revenue > 0 && margin !== null ? Math.round((margin / revenue) * 10000) : null

  return {
    id,
    clientId,
    clientName,
    contractName,
    objectName,
    city,
    coordinator,
    currency: 'PLN',
    revenueMinor: money(revenue),
    laborCostMinor: Number.isFinite(labor) ? money(labor) : null,
    materialCostMinor: Number.isFinite(materials) ? money(materials) : null,
    equipmentCostMinor: Number.isFinite(equipment) ? money(equipment) : null,
    otherCostMinor: Number.isFinite(other) ? money(other) : null,
    totalCostMinor: totalCost === null ? null : money(totalCost),
    marginMinor: margin === null ? null : money(margin),
    profitabilityBps: profitabilityBps === null ? null : String(profitabilityBps),
    targetProfitabilityBps: String(targetBps),
    plannedMinutes: String(Math.round(plannedHours * 60)),
    actualMinutes: String(Math.round(actualHours * 60)),
    completenessPercent: completeness,
    status,
    issues,
    note,
  }
}

export function createContractProfitabilityPreviewPayload() {
  const months = [
    '2025-08', '2025-09', '2025-10', '2025-11', '2025-12', '2026-01',
    '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07',
  ]
  const revenue = [372000, 381000, 389000, 395000, 408000, 411000, 419000, 426000, 433000, 441000, 448000, 456000]
  const totalCost = [346000, 351000, 354000, 361000, 370000, 374000, 379000, 384000, 391000, 395000, 399000, 403400]

  return {
    period: '2026-07',
    currency: 'PLN',
    trend: months.map((period, index) => {
      const margin = revenue[index] - totalCost[index]
      return {
        period,
        revenueMinor: money(revenue[index]),
        totalCostMinor: money(totalCost[index]),
        marginMinor: money(margin),
        profitabilityBps: String(Math.round((margin / revenue[index]) * 10000)),
      }
    }),
    contracts: [
      contract({
        id: 'DEMO-BC-01',
        clientId: 'DEMO-CLIENT-01',
        clientName: 'Nova Office',
        contractName: 'BC/2026/07',
        objectName: 'Biurowiec Centrum',
        city: 'Katowice',
        coordinator: 'Anna Maj',
        revenue: 150000,
        labor: 82000,
        materials: 9000,
        equipment: 5000,
        other: 14000,
        targetBps: 2000,
        plannedHours: 900,
        actualHours: 930,
        completeness: 100,
        status: 'ABOVE_TARGET',
        note: 'Wynik powyżej celu mimo przekroczenia czasu o 30 godzin.',
      }),
      contract({
        id: 'DEMO-GP-02',
        clientId: 'DEMO-CLIENT-02',
        clientName: 'Galeria Północ',
        contractName: 'GHP/2026',
        objectName: 'Galeria Handlowa Północ',
        city: 'Gliwice',
        coordinator: 'Marek Wilk',
        revenue: 90000,
        labor: 62000,
        materials: 7000,
        equipment: 3000,
        other: 6000,
        targetBps: 1800,
        plannedHours: 650,
        actualHours: 690,
        completeness: 100,
        status: 'BELOW_TARGET',
        issues: ['Koszt pracy przekroczył plan o 40 godzin.'],
        note: 'Największym obciążeniem pozostaje koszt pracy weekendowej.',
      }),
      contract({
        id: 'DEMO-ML-03',
        clientId: 'DEMO-CLIENT-03',
        clientName: 'Logis Park',
        contractName: 'ML/2026',
        objectName: 'Magazyn Logistyczny',
        city: 'Tychy',
        coordinator: 'Anna Maj',
        revenue: 60000,
        labor: 36000,
        materials: 4000,
        equipment: 2000,
        other: 5000,
        targetBps: 2200,
        plannedHours: 420,
        actualHours: 410,
        completeness: 97,
        status: 'BELOW_TARGET',
        issues: ['Brakuje dokumentu źródłowego dla jednego kosztu materiałów.'],
        note: 'Czas pracy jest poniżej planu, ale rentowność pozostaje lekko poniżej celu.',
      }),
      contract({
        id: 'DEMO-ZP-04',
        clientId: 'DEMO-CLIENT-04',
        clientName: 'ProTech',
        contractName: 'ZP/2026/04',
        objectName: 'Zakład Produkcyjny',
        city: 'Rybnik',
        coordinator: 'Joanna Lis',
        revenue: 72000,
        labor: 48000,
        materials: 8000,
        equipment: 3500,
        other: 15900,
        targetBps: 1800,
        plannedHours: 520,
        actualHours: 604,
        completeness: 100,
        status: 'NEGATIVE',
        issues: ['Rzeczywisty czas przekroczył plan o 84 godziny.', 'Koszt interwencji nie został przeniesiony na klienta.'],
        note: 'Kontrakt wymaga korekty obsady albo renegocjacji zakresu.',
      }),
      contract({
        id: 'DEMO-UM-05',
        clientId: 'DEMO-CLIENT-05',
        clientName: 'Urząd Miasta',
        contractName: 'UM/2026',
        objectName: 'Urząd Miasta',
        city: 'Żory',
        coordinator: 'Marek Wilk',
        revenue: 52000,
        labor: null,
        materials: 4800,
        equipment: 1500,
        other: 4200,
        targetBps: 1600,
        plannedHours: 430,
        actualHours: 447,
        completeness: 76,
        status: 'INCOMPLETE',
        issues: ['Brak stawki kosztowej dla dwóch pracowników.', 'Jeden dzień pracy nie ma zamkniętego STOP.'],
        note: 'Wynik pozostaje ukryty, dopóki nie zostaną uzupełnione koszty pracy.',
      }),
      contract({
        id: 'DEMO-HP-06',
        clientId: 'DEMO-CLIENT-06',
        clientName: 'Hotel Park',
        contractName: 'HP/2026/DOD',
        objectName: 'Hotel Park',
        city: 'Bielsko-Biała',
        coordinator: 'Joanna Lis',
        revenue: 0,
        labor: 18000,
        materials: 2500,
        equipment: 1000,
        other: 3500,
        targetBps: 1800,
        plannedHours: 190,
        actualHours: 205,
        completeness: 100,
        status: 'NOT_CALCULABLE',
        issues: ['Brak zaksięgowanego przychodu za usługę dodatkową.'],
        note: 'Koszty są znane, ale bez przychodu nie można wyliczyć rentowności procentowej.',
      }),
      contract({
        id: 'DEMO-CM-07',
        clientId: 'DEMO-CLIENT-07',
        clientName: 'MediCare',
        contractName: 'CM/2026',
        objectName: 'Centrum Medyczne',
        city: 'Katowice',
        coordinator: 'Anna Maj',
        revenue: 84000,
        labor: 50000,
        materials: 6000,
        equipment: 4500,
        other: 7500,
        targetBps: 1800,
        plannedHours: 560,
        actualHours: 552,
        completeness: 100,
        status: 'ABOVE_TARGET',
        note: 'Kontrakt realizowany zgodnie z planem i powyżej ustalonego celu.',
      }),
    ],
  }
}
