'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('migracja reconciliation jest addytywna, idempotentna i nie poprawia danych historycznych', () => {
  const sql = fs.readFileSync(
    path.join(__dirname, '..', 'dataconnect', 'migrations', '20260803_workday_reconciliation_additive.sql'),
    'utf8',
  )
  assert.match(sql, /add column if not exists business_date_ymd/i)
  assert.match(sql, /create table if not exists public\.workday_reconciliation_audit/i)
  assert.match(sql, /create unique index if not exists workday_reconciliation_audit_idempotency_idx/i)
  assert.match(sql, /alter table public\.workday_reconciliation_audit[\s\S]*add column if not exists org_id/i)
  assert.match(sql, /add constraint workday_reconciliation_audit_request_hash_check/i)
  assert.match(sql, /add constraint workday_reconciliation_audit_action_check/i)
  assert.match(sql, /add constraint workday_reconciliation_audit_reason_check/i)
  assert.match(sql, /convalidated/i)
  assert.match(sql, /add constraint workday_business_date_ymd_check/i)
  assert.match(sql, /business_date_ymd is null[\s\S]*\^\[0-9\]\{4\}[\s\S]*to_date\(business_date_ymd, 'YYYY-MM-DD'\)/i)
  assert.match(sql, /create or replace function public\.set_workday_business_date\(\)/i)
  assert.match(sql, /before insert or update of start_at, business_date_ymd on public\.workday/i)
  assert.match(sql, /nullif\(btrim\(new\.business_date_ymd\), ''\) is null/i)
  assert.match(sql, /new\.start_at at time zone 'Europe\/Warsaw'/i)
  assert.match(sql, /workday_reconciliation_audit_reject_update/i)
  assert.match(sql, /workday_reconciliation_audit_reject_delete/i)
  assert.match(sql, /workday_reconciliation_audit_reject_truncate[\s\S]*before truncate on public\.workday_reconciliation_audit/i)
  assert.match(sql, /pg_get_indexdef\(index_meta\.indexrelid, 1, true\) = 'org_id'/i)
  assert.match(sql, /pg_get_indexdef\(index_meta\.indexrelid, 2, true\) = 'idempotency_key'/i)
  assert.match(sql, /pg_get_indexdef\(constraint_meta\.conindid, 1, true\) = 'org_id'/i)
  assert.match(sql, /pg_get_indexdef\(constraint_meta\.conindid, 2, true\) = 'audit_id'/i)
  assert.match(sql, /tgfoid = 'public\.set_workday_business_date\(\)'::regprocedure[\s\S]*tgtype = 23/i)
  assert.doesNotMatch(sql, /moĹ|Ä‡|Ä™|Ĺ‚|Ĺ›/)
  assert.doesNotMatch(sql, /update\s+public\.(?:workday|event)\b/i)
  assert.doesNotMatch(sql, /delete\s+from\s+public\.(?:workday|event)\b/i)
})

test('raport historyczny dziala w transakcji READ ONLY i wykrywa wymagane klasy bledow', () => {
  const sql = fs.readFileSync(
    path.join(__dirname, '..', 'scripts', 'audit-workday-reconciliation.sql'),
    'utf8',
  )
  assert.match(sql, /begin transaction isolation level repeatable read read only/i)
  assert.match(sql, /CLOSED_WORKDAY_WITH_OPEN_SESSION/)
  assert.match(sql, /WORKDAY_DURATION_MISMATCH/)
  assert.match(sql, /SESSION_BUSINESS_DATE_MISMATCH/)
  assert.match(sql, /SESSION_WORKER_MISMATCH/)
  assert.match(sql, /SESSION_TIMESTAMP_MISSING/)
  assert.match(sql, /SESSION_FUTURE_TIMESTAMP/)
  assert.match(sql, /SESSION_DURATION_EXCEEDED/)
  assert.match(sql, /SEMANTIC_DUPLICATE_SESSION/)
  assert.match(sql, /SESSION_OVERLAP/)
  assert.doesNotMatch(sql, /MULTIPLE_WORKDAYS_FOR_BUSINESS_DATE/)
  assert.match(sql, /to_jsonb\(w\)\s*->>\s*'business_date_ymd'/i)
  assert.match(sql, /merged_closed_events/i)
  assert.match(sql, /event_totals[\s\S]*from workday_dates w/i)
  assert.match(sql, /e\.end_at - e\.start_at <= interval '24 hours'/i)
  assert.match(sql, /e\.end_at <= current_timestamp/i)
  assert.match(sql, /to_char\(e\.start_at at time zone 'Europe\/Warsaw', 'YYYY-MM-DD'\)[\s\S]*= w\.canonical_business_date_ymd/i)
  assert.match(sql, /btrim\(e\.worker_login\) = btrim\(w\.worker_login\)/i)
  assert.match(sql, /floor\(sum\(extract\(epoch from \(merged\.end_at - merged\.start_at\)\)\)\)::bigint/i)
  assert.doesNotMatch(sql, /sum\(floor\(extract\(epoch from \(merged\.end_at - merged\.start_at\)\)\)::bigint\)/i)
  assert.match(sql, /right_event\.workday_worker_login = left_event\.workday_worker_login/i)
  assert.match(sql, /right_event\.canonical_business_date_ymd = left_event\.canonical_business_date_ymd/i)
  assert.doesNotMatch(sql, /right_event\.workday_id = left_event\.workday_id/i)
  assert.match(sql, /canonical_business_date_ymd/i)
  assert.match(sql, /rollback;/i)
  assert.doesNotMatch(sql, /\b(?:insert|update|delete|alter|create|drop|truncate)\b\s+(?:into\s+|table\s+|from\s+)?public\./i)
})
