import { STYLE_FALLBACK_ID } from '../../services/styleService'

export function createAppState(overrides = {}) {
  return {

  session: null,
  clients: [],
  clientsLoaded: false,
  clientsPage: 1,
  clientsPageSize: 50,
  clientsTotal: 0,
  clientsTotalPages: 1,
  clientModalMode: 'add',
  clientModalClientId: '',
  zones: [],
  zonesLoaded: false,
  zonesPage: 1,
  zonesPageSize: 50,
  zonesTotal: 0,
  zonesTotalPages: 1,
  workers: [],
  workersLoaded: false,
  workerTimeRows: [],
  workerTimeViewRows: [],
  workerTimeSelectedKeys: new Set(),
  workerTimeCurrentPageKeys: [],
  workersPage: 1,
  workersPageSize: 50,
  workersTotal: 0,
  workersTotalPages: 1,
  eventsPage: 1,
  eventsPageSize: 50,
  eventsTotal: 0,
  eventsTotalPages: 1,
  eventsFilters: null,
  eventsWorkerLoginFilter: '',
  eventsWorkerLoginFilterText: '',
  eventsSelectedKeys: new Set(),
  eventRows: [],
  ordersSearch: '',
  ordersShowCyclic: false,
  ordersListModel: 'all',
  ordersListStatus: '',
  ordersListType: '',
  ordersListAssignment: '',
  ordersListQuickFilter: 'all',
  ordersListDateFrom: '',
  ordersListDateTo: '',
  ordersListClient: '',
  ordersListWorker: '',
  ordersListSort: 'nextAsc',
  ordersEditingId: '',
  ordersEditorMode: 'edit',
  ordersEditorTab: 'basic',
  ordersEditorStep: 'client',
  ordersClientCreateReturnOrderId: '',
  ordersRepeatCalendarMonth: '',
  ordersObjectPlanZoneKey: '',
  ordersObjectPlanCalendarMonth: '',
  ordersObjectPlanDraggingTaskId: '',
  ordersServiceBlockDraggingKind: '',
  ordersObjectPlanSelectedZoneKeys: [],
  ordersObjectPlanDayEditorDate: '',
  ordersObjectPlanZoneWindowOpen: false,
  ordersObjectPlanTaskWindowOpen: false,
  ordersMapDateFrom: '',
  ordersMapDateTo: '',
  ordersMapStatus: 'new',
  ordersMapType: '',
  ordersMapWorker: '',
  ordersMapWorkerOnly: true,
  ordersMapSearch: '',
  calendarTasks: [],
  calendarRemoteTasksLoaded: false,
  calendarRemoteTasksLoading: false,
  calendarViewMode: 'three',
  calendarCursorDay: '',
  calendarEditorTaskId: '',
  calendarEditorTab: 'comments',
  calendarDragTaskId: '',
  calendarToneFilters: ['blue', 'green', 'amber', 'red', 'message'],
  calendarShowCompletedTasks: false,
  calendarShowReadTasks: false,
  calendarTimelineHourTimer: null,
  calendarTimelineSlideDirection: 0,
  calendarTimelineResetScroll: false,
  calendarTimelineShowCompleted: true,
  calendarTimelineTypeFilters: ['individual', 'cyclic', 'renovation', 'windows', 'other'],
  calendarTimelineDemoOrders: [],
  calendarTimelineOrdersRemoteLoaded: false,
  calendarTimelineOrdersRemoteLoading: false,
  calendarTimelineDragOrderId: '',
  calendarTimelineDragSourceRow: null,
  calendarTimelineDragSourceOrderId: '',
  calendarTimelineDragOccurrenceDate: '',
  calendarTimelineDragWorkSlotKey: '',
  calendarTimelineDragRecurringSeries: false,
  calendarTimelineDragTargetRow: null,
  calendarTimelineDragTargetSlot: null,
  calendarTimelineDropHandled: false,
  calendarTimelineDragResources: [],
  calendarTimelineDragConflictKey: '',
  calendarTimelineDragConflictValue: false,
  calendarTimelineDragHoverKey: '',
  calendarTimelineDragHoverInvalid: false,
  calendarTimelineDragHoverNode: null,
  calendarTimelineVisibleConflictItems: [],
  calendarTimelineWorkerStateLoading: false,
  calendarTimelineWorkerStateRefreshQueued: false,
  calendarTimelineWorkerStateFetchedAt: 0,
  calendarTimelineWorkerStateDayKey: '',
  calendarTimelineWorkerStateRangeStart: '',
  calendarTimelineWorkerStateRangeEnd: '',
  calendarTimelineWorkerStateRows: [],
  calendarTimelineWorkerStateSourceRows: [],
  calendarTimelineCurrentWorkerStatusDayKey: '',
  calendarTimelineCurrentWorkerStatusRows: [],
  calendarTimelineStatusAlerts: [],
  calendarTimelineStatusAlertShownKeys: new Set(),
  calendarTimelineStageHeight: 0,
  calendarTimelinePlannedLaneCounts: new Map(),
  calendarTimelineRealTrackCounts: new Map(),
  calendarTimelineLaneCounts: new Map(),
  calendarTimelineDeltaCounts: new Map(),
  kanbanColumns: [],
  kanbanColumnEditorMode: 'add',
  kanbanColumnEditorId: '',
  kanbanColumnDeleteConfirm: false,
  kanbanSearch: '',
  kanbanSection: 'home',
  kanbanHomeTaskTab: 'upcoming',
  kanbanInboxTab: 'activity',
  kanbanProjectLimit: 9,
  kanbanDragColumnId: '',
  kanbanDragTaskId: '',
  kanbanPendingStatus: '',
  kanbanDoneTaskId: '',
  kanbanDataLoading: false,
  kanbanDataLoadingText: '',
  workerDetailPage: 1,
  workerDetailPageSize: 50,
  workerDetailRows: [],
  workerDetailSourceRows: [],
  workerDetailViewRows: [],
  workerDetailSelectedKeys: new Set(),
  workerDetailCurrentPageKeys: [],
  workerDetailDayEditorItem: null,
  workerDetailAckMap: {},
  workerDetailColumnWidthsLoaded: false,
  workerDetailColumnWidths: [],
  workerProfilePage: 1,
  workerProfilePageSize: 50,
  workerProfileTotal: 0,
  workerProfileTotalPages: 1,
  workerProfileSort: 'nameAsc',
  selectedWorkerLogin: '',
  selectedWorkerName: '',
  workerAccountCurrent: null,
  workerAccountActiveTab: 'account',
  workerAccountTargetKey: '',
  workerAccountCurrentKey: '',
  workerAccountRequestSeq: 0,
  workerAccountLoadedWorkerKey: '',
  workerAccountDataLoadingKey: '',
  workerAccountSummaryLoadingKey: '',
  workerAccountOrdersLoadingKey: '',
  workerAccountActivityLoadingKey: '',
  workerAccountTimeLoadingKey: '',
  workerAccountSummaryLoadedKey: '',
  workerAccountOrdersLoadedKey: '',
  workerAccountActivityLoadedKey: '',
  workerAccountTimeLoadedKey: '',
  workerAccountOrderRows: [],
  workerAccountEventsRows: [],
  workerAccountDaysRows: [],
  workerAccountAllTimeRows: [],
  workerAccountTimeRows: [],
  workerAccountTimeSelectedKeys: new Set(),
  workerAccountTimeCurrentPageKeys: [],
  workerAccountEventsPage: 1,
  workerAccountEventsPageSize: 5,
  workerAccountOrdersPage: 1,
  workerAccountOrdersPageSize: 5,
  workerAccountDaysPage: 1,
  workerAccountDaysPageSize: 5,
  workerAccountTimePage: 1,
  workerAccountTimePageSize: 50,
  zoneModalMode: 'add',
  zoneModalZoneId: '',
  eventEditorMode: 'add',
  eventEditorItem: null,
  eventEditorWorkerOptions: [],
  eventEditorClientOptions: [],
  eventEditorZoneOptions: [],
  workerProfileRows: [],
  workerProfileViewRows: [],
  workerProfileModalMode: 'view',
  workerProfileCurrent: null,
  clientProfileRows: [],
  clientProfileCurrent: null,
  clientProfileEditMode: false,
  clientProfileActiveTab: 'profile',
  clientProfileCalendarInstance: null,
  clientProfileCalendarRows: [],
  clientProfileAssignSelectedKeys: new Set(),
  clientProfileCoordinatorSelectedKey: '',
  clientProfileEditAssignees: '',
  reportLastCsv: '',
  reportHistoryTab: 'objects',
  reportHistoryRows: [],
  reportHistoryExpanded: {},
  reportHistoryEditableMap: {},
  reportHistoryClosingDayKey: '',
  reportHistoryClientOptions: [],
  reportHistoryWorkerOptions: [],
  reportHistoryZoneOptions: [],
  dashboardMetricDetails: {},
  dashboardMetricValues: {},
  dashboardTodayRows: [],
  dashboardActivityWorkdayRows: [],
  dashboardActivityView: 'today-calendar',
  dashboardActivityDay: '',
  dashboardActivityDayRows: [],
  dashboardActivityDaySourceRows: [],
  dashboardActivityDayLoading: false,
  dashboardActivityDayRequestKey: '',
  dashboardNewComments: [],
  dashboardScheduleDays: [],
  dashboardScheduleSelectedDay: '',
  dashboardScheduleFetchedAt: '',
  dashboardScheduleLoading: false,
  dashboardScheduleError: '',
  dashboardScheduleStale: false,
  dashboardScheduleSourceRows: [],
  dashboardBackgroundDataLoaded: false,
  dashboardScheduleAlertSnoozeUntil: 0,
  dashboardScheduleAlertMuted: false,
  dashboardScheduleAlertLastKey: '',
  dashboardScheduleLateShownKeys: new Set(),
  dashboardScheduleLatePendingKeys: [],
  dashboardLoadingCount: 0,
  settingsActiveTab: 'styles',
  settingsEffectiveStyleId: STYLE_FALLBACK_ID,
  settingsEffectiveStyleSource: 'fallback',
  settingsOrgStyleId: '',
  settingsUserStyleId: '',
  settingsBackups: [],
  settingsImportInspection: null,
  settingsAutomationDayKey: '',
  currentRoute: '',

    ...overrides,
  }
}

export const appState = createAppState()

export function resetAppState(overrides = {}) {
  const nextState = createAppState(overrides)
  Object.keys(appState).forEach((key) => {
    delete appState[key]
  })
  Object.assign(appState, nextState)
  return appState
}

export function resetDashboardState(state = appState) {
  Object.assign(state, {
    dashboardMetricDetails: {},
    dashboardMetricValues: {},
    dashboardTodayRows: [],
    dashboardActivityWorkdayRows: [],
    dashboardActivityDay: '',
    dashboardActivityDayRows: [],
    dashboardActivityDaySourceRows: [],
    dashboardActivityDayLoading: false,
    dashboardActivityDayRequestKey: '',
    dashboardNewComments: [],
    dashboardScheduleDays: [],
    dashboardScheduleSelectedDay: '',
    dashboardScheduleFetchedAt: '',
    dashboardScheduleLoading: false,
    dashboardScheduleError: '',
    dashboardScheduleStale: false,
    dashboardScheduleSourceRows: [],
    dashboardBackgroundDataLoaded: false,
    dashboardScheduleAlertSnoozeUntil: 0,
    dashboardScheduleAlertMuted: false,
    dashboardScheduleAlertLastKey: '',
    dashboardScheduleLateShownKeys: new Set(),
    dashboardScheduleLatePendingKeys: [],
    dashboardLoadingCount: 0,
  })
  return state
}

export function resetSessionState(overrides = {}) {
  return resetAppState(overrides)
}
