export const ISSA_NORM_CATALOG_V1 = Object.freeze({
  schemaVersion: '1.0.0',
  catalogVersion: '2026-07-28.1',
  status: 'PARTIAL_VERIFIED',
  language: 'pl',
  source: Object.freeze({
    sourceId: 'ISSA-612-PL-BEN-WALKER',
    title: '612 oficjalnych norm czasu sprzątania ISSA',
    author: 'Ben Walker',
    fileName: 'Normy_ISSA_do_druku_A4.pdf',
    sha256: '7F881D963D82C9B1D0AF35AD6F6F4873455B9037E3BA4601AAECD215A792D612',
    pdfPageCount: 39,
    suppliedByUser: true,
    sourceFileEmbedded: false,
    formula: Object.freeze({
      pdfPage: 39,
      printedPage: 57,
      description: '60 / czas ISSA w minutach × powierzchnia referencyjna = m² na godzinę',
    }),
  }),
  coverage: Object.freeze({
    verifiedPdfPages: Object.freeze([6, 39]),
    verifiedTaskNumbers: Object.freeze(Array.from({ length: 24 }, (_, index) => index + 50)),
    note: 'Aktywny kalkulator korzysta wyłącznie z rekordów zweryfikowanych wzrokowo. Pozostałe strony PDF wymagają osobnej kontroli przed publikacją w katalogu.',
  }),
  norms: Object.freeze([
    {
      id: 'ISSA-050',
      taskNumber: 50,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu miotełką / starcie tablicy / starcie kurzu mopem z podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 9.4,
      productivity: { value: 593, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-051',
      taskNumber: 51,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu miotełką / starcie tablicy / przetarcie wilgotnym mopem podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 16,
      productivity: { value: 348, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-052',
      taskNumber: 52,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu miotełką / starcie tablicy / odkurzanie odkurzaczem kubełkowym podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 12.2,
      productivity: { value: 457, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-053',
      taskNumber: 53,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu miotełką / starcie tablicy / odkurzenie podłogi odkurzaczem pionowym',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 14,
      productivity: { value: 398, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-054',
      taskNumber: 54,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu nasączoną szmatką / starcie tablicy / przetarcie podłogi mopem',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 10.4,
      productivity: { value: 536, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-055',
      taskNumber: 55,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu nasączoną szmatką / starcie tablicy / przetarcie wilgotnym mopem podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 17,
      productivity: { value: 328, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-056',
      taskNumber: 56,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu nasączoną szmatką / starcie tablicy / odkurzanie odkurzaczem kubełkowym podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 14.6,
      productivity: { value: 382, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-057',
      taskNumber: 57,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu nasączoną szmatką / starcie tablicy / odkurzenie podłogi odkurzaczem pionowym',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 15.4,
      productivity: { value: 362, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-058',
      taskNumber: 58,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / odkurzanie odkurzaczem z „wyłapywarką” / starcie tablicy / odkurzanie odkurzaczem przenośnym podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 10.5,
      productivity: { value: 531, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-059',
      taskNumber: 59,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Wyrzucenie śmieci / starcie kurzu odkurzaczem plecakowym / starcie tablicy / odkurzenie odkurzaczem plecakowym podłogi',
      basis: { type: 'AREA', quantity: 92.9, unit: 'M2' },
      referenceMinutes: 11,
      productivity: { value: 507, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-060',
      taskNumber: 60,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Umycie 24 biurek szkolnych za pomocą aplikatora i myjki',
      basis: { type: 'COUNT', quantity: 24, unit: 'DESK' },
      referenceMinutes: 4,
      productivity: null,
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-061',
      taskNumber: 61,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'SPRZĄTANIE W KLASIE',
      description: 'Umycie 24 biurek szkolnych za pomocą aplikatora i gąbki',
      basis: { type: 'COUNT', quantity: 24, unit: 'DESK' },
      referenceMinutes: 6,
      productivity: null,
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-062',
      taskNumber: 62,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'ROGI / ZAGŁĘBIENIA',
      description: 'Sprzątanie szczegółowe spryskiwaczem i szmatką',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 4.5,
      productivity: { value: 186, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-063',
      taskNumber: 63,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'ROGI / ZAGŁĘBIENIA',
      description: 'Sprzątanie szczegółowe odkurzaczem ręcznym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 3.8,
      productivity: { value: 220, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-064',
      taskNumber: 64,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'ROGI / ZAGŁĘBIENIA',
      description: 'Sprzątanie szczegółowe odkurzaczem kubełkowym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 4.05,
      productivity: { value: 206, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-065',
      taskNumber: 65,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'ROGI / ZAGŁĘBIENIA',
      description: 'Sprzątanie szczegółowe odkurzaczem plecakowym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 3.15,
      productivity: { value: 265, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-066',
      taskNumber: 66,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'ROGI / ZAGŁĘBIENIA',
      description: 'Czyszczenie szczegółowe fug za pomocą akumulatorowej szorowarki typu Sonic i środka chemicznego',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 3.15,
      productivity: { value: 265, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-067',
      taskNumber: 67,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'DEZYNFEKCJA POWIERZCHNI',
      description: 'Przetarcie na mokro powierzchni środkiem dezynfekującym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 2.88,
      productivity: { value: 290, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-068',
      taskNumber: 68,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Starcie kurzu miotełką',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 0.9,
      productivity: { value: 929, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-069',
      taskNumber: 69,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Starcie kurzu nasączoną szmatką',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 1.8,
      productivity: { value: 465, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-070',
      taskNumber: 70,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Przetarcie na mokro spryskiwaczem i szmatką',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 2.88,
      productivity: { value: 290, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-071',
      taskNumber: 71,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Odkurzanie odkurzaczem ręcznym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 1.95,
      productivity: { value: 429, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-072',
      taskNumber: 72,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Odkurzanie odkurzaczem kubełkowym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 2.25,
      productivity: { value: 372, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
    {
      id: 'ISSA-073',
      taskNumber: 73,
      category: 'OGÓLNE SPRZĄTANIE',
      subcategory: 'USUWANIE KURZU Z POWIERZCHNI',
      description: 'Odkurzanie odkurzaczem plecakowym',
      basis: { type: 'AREA', quantity: 13.9, unit: 'M2' },
      referenceMinutes: 1.62,
      productivity: { value: 516, unit: 'M2_PER_HOUR' },
      source: { pdfPage: 6, printedPage: 12 },
      verificationStatus: 'VERIFIED_VISUALLY',
    },
  ].map((norm) => Object.freeze({
    ...norm,
    basis: Object.freeze({ ...norm.basis }),
    productivity: norm.productivity ? Object.freeze({ ...norm.productivity }) : null,
    source: Object.freeze({ ...norm.source }),
  }))),
})
