import { InsertWorkerForOrgData, InsertWorkerForOrgVariables, InsertWorkerWithMembershipForOrgData, InsertWorkerWithMembershipForOrgVariables, UpdateWorkerForOrgData, UpdateWorkerForOrgVariables, UpdateWorkerProfileForOrgData, UpdateWorkerProfileForOrgVariables, RenameWorkerForOrgData, RenameWorkerForOrgVariables, DeleteWorkerProfileForOrgData, DeleteWorkerProfileForOrgVariables, UpsertWorkerCredentialForOrgData, UpsertWorkerCredentialForOrgVariables, UpsertOrgUiStyleForOrgData, UpsertOrgUiStyleForOrgVariables, DeleteOrgUiStyleForOrgData, DeleteOrgUiStyleForOrgVariables, UpsertMyUiStylePreferenceData, UpsertMyUiStylePreferenceVariables, DeleteMyUiStylePreferenceData, DeleteMyUiStylePreferenceVariables, UpsertUserUiStylePreferenceForOrgData, UpsertUserUiStylePreferenceForOrgVariables, DeleteUserUiStylePreferenceForOrgData, DeleteUserUiStylePreferenceForOrgVariables, InsertClientForOrgData, InsertClientForOrgVariables, UpdateClientForOrgData, UpdateClientForOrgVariables, DeleteClientForOrgData, DeleteClientForOrgVariables, InsertIndividualJobForOrgData, InsertIndividualJobForOrgVariables, UpdateIndividualJobForOrgData, UpdateIndividualJobForOrgVariables, DeleteIndividualJobForOrgData, DeleteIndividualJobForOrgVariables, UpsertTaskForOrgData, UpsertTaskForOrgVariables, DeleteTaskForOrgData, DeleteTaskForOrgVariables, InsertZoneForOrgData, InsertZoneForOrgVariables, UpdateZoneForOrgData, UpdateZoneForOrgVariables, DeleteZoneForOrgData, DeleteZoneForOrgVariables, InsertWorkdayForOrgData, InsertWorkdayForOrgVariables, UpdateWorkdayForOrgData, UpdateWorkdayForOrgVariables, DeleteWorkdayForOrgData, DeleteWorkdayForOrgVariables, InsertEventForOrgData, InsertEventForOrgVariables, UpdateEventForOrgData, UpdateEventForOrgVariables, DeleteEventForOrgData, DeleteEventForOrgVariables, InsertBackupCycleForOrgData, InsertBackupCycleForOrgVariables, UpdateBackupCycleForOrgData, UpdateBackupCycleForOrgVariables, InsertStorageForOrgData, InsertStorageForOrgVariables, UpdateStorageForOrgData, UpdateStorageForOrgVariables, DeleteStorageForOrgData, DeleteStorageForOrgVariables, InsertClientStorageForOrgData, InsertClientStorageForOrgVariables, UpdateClientStorageForOrgData, UpdateClientStorageForOrgVariables, DeleteClientStorageForOrgData, DeleteClientStorageForOrgVariables, StartWorkdayPauseData, StartWorkdayPauseVariables, StopWorkdayPauseData, StopWorkdayPauseVariables, MyOrganizationsData, OrgUiStyleForOrgData, OrgUiStyleForOrgVariables, MyUiStylePreferenceData, MyUiStylePreferenceVariables, UserUiStylePreferencesForOrgData, UserUiStylePreferencesForOrgVariables, CanManageWorkersForOrgData, CanManageWorkersForOrgVariables, WorkersForOrgData, WorkersForOrgVariables, AdminWorkerCredentialForOrgData, AdminWorkerCredentialForOrgVariables, ClientsForOrgData, ClientsForOrgVariables, IndividualJobsForOrgData, IndividualJobsForOrgVariables, TasksForOrgData, TasksForOrgVariables, ZonesForOrgData, ZonesForOrgVariables, WorkdaysForOrgData, WorkdaysForOrgVariables, BackupCyclesForOrgData, BackupCyclesForOrgVariables, EventsForOrgData, EventsForOrgVariables, WorkerWorkdaysForOrgData, WorkerWorkdaysForOrgVariables, StorageForOrgData, StorageForOrgVariables, ClientStorageForClientData, ClientStorageForClientVariables, ClientStorageForOrgData, ClientStorageForOrgVariables, WorkdayPausesForOrgData, WorkdayPausesForOrgVariables, ActiveWorkdayPauseForWorkerData, ActiveWorkdayPauseForWorkerVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useInsertWorkerForOrg(options?: useDataConnectMutationOptions<InsertWorkerForOrgData, FirebaseError, InsertWorkerForOrgVariables>): UseDataConnectMutationResult<InsertWorkerForOrgData, InsertWorkerForOrgVariables>;
export function useInsertWorkerForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertWorkerForOrgData, FirebaseError, InsertWorkerForOrgVariables>): UseDataConnectMutationResult<InsertWorkerForOrgData, InsertWorkerForOrgVariables>;

export function useInsertWorkerWithMembershipForOrg(options?: useDataConnectMutationOptions<InsertWorkerWithMembershipForOrgData, FirebaseError, InsertWorkerWithMembershipForOrgVariables>): UseDataConnectMutationResult<InsertWorkerWithMembershipForOrgData, InsertWorkerWithMembershipForOrgVariables>;
export function useInsertWorkerWithMembershipForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertWorkerWithMembershipForOrgData, FirebaseError, InsertWorkerWithMembershipForOrgVariables>): UseDataConnectMutationResult<InsertWorkerWithMembershipForOrgData, InsertWorkerWithMembershipForOrgVariables>;

export function useUpdateWorkerForOrg(options?: useDataConnectMutationOptions<UpdateWorkerForOrgData, FirebaseError, UpdateWorkerForOrgVariables>): UseDataConnectMutationResult<UpdateWorkerForOrgData, UpdateWorkerForOrgVariables>;
export function useUpdateWorkerForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateWorkerForOrgData, FirebaseError, UpdateWorkerForOrgVariables>): UseDataConnectMutationResult<UpdateWorkerForOrgData, UpdateWorkerForOrgVariables>;

export function useUpdateWorkerProfileForOrg(options?: useDataConnectMutationOptions<UpdateWorkerProfileForOrgData, FirebaseError, UpdateWorkerProfileForOrgVariables>): UseDataConnectMutationResult<UpdateWorkerProfileForOrgData, UpdateWorkerProfileForOrgVariables>;
export function useUpdateWorkerProfileForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateWorkerProfileForOrgData, FirebaseError, UpdateWorkerProfileForOrgVariables>): UseDataConnectMutationResult<UpdateWorkerProfileForOrgData, UpdateWorkerProfileForOrgVariables>;

export function useRenameWorkerForOrg(options?: useDataConnectMutationOptions<RenameWorkerForOrgData, FirebaseError, RenameWorkerForOrgVariables>): UseDataConnectMutationResult<RenameWorkerForOrgData, RenameWorkerForOrgVariables>;
export function useRenameWorkerForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<RenameWorkerForOrgData, FirebaseError, RenameWorkerForOrgVariables>): UseDataConnectMutationResult<RenameWorkerForOrgData, RenameWorkerForOrgVariables>;

export function useDeleteWorkerProfileForOrg(options?: useDataConnectMutationOptions<DeleteWorkerProfileForOrgData, FirebaseError, DeleteWorkerProfileForOrgVariables>): UseDataConnectMutationResult<DeleteWorkerProfileForOrgData, DeleteWorkerProfileForOrgVariables>;
export function useDeleteWorkerProfileForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteWorkerProfileForOrgData, FirebaseError, DeleteWorkerProfileForOrgVariables>): UseDataConnectMutationResult<DeleteWorkerProfileForOrgData, DeleteWorkerProfileForOrgVariables>;

export function useUpsertWorkerCredentialForOrg(options?: useDataConnectMutationOptions<UpsertWorkerCredentialForOrgData, FirebaseError, UpsertWorkerCredentialForOrgVariables>): UseDataConnectMutationResult<UpsertWorkerCredentialForOrgData, UpsertWorkerCredentialForOrgVariables>;
export function useUpsertWorkerCredentialForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertWorkerCredentialForOrgData, FirebaseError, UpsertWorkerCredentialForOrgVariables>): UseDataConnectMutationResult<UpsertWorkerCredentialForOrgData, UpsertWorkerCredentialForOrgVariables>;

export function useUpsertOrgUiStyleForOrg(options?: useDataConnectMutationOptions<UpsertOrgUiStyleForOrgData, FirebaseError, UpsertOrgUiStyleForOrgVariables>): UseDataConnectMutationResult<UpsertOrgUiStyleForOrgData, UpsertOrgUiStyleForOrgVariables>;
export function useUpsertOrgUiStyleForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertOrgUiStyleForOrgData, FirebaseError, UpsertOrgUiStyleForOrgVariables>): UseDataConnectMutationResult<UpsertOrgUiStyleForOrgData, UpsertOrgUiStyleForOrgVariables>;

export function useDeleteOrgUiStyleForOrg(options?: useDataConnectMutationOptions<DeleteOrgUiStyleForOrgData, FirebaseError, DeleteOrgUiStyleForOrgVariables>): UseDataConnectMutationResult<DeleteOrgUiStyleForOrgData, DeleteOrgUiStyleForOrgVariables>;
export function useDeleteOrgUiStyleForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteOrgUiStyleForOrgData, FirebaseError, DeleteOrgUiStyleForOrgVariables>): UseDataConnectMutationResult<DeleteOrgUiStyleForOrgData, DeleteOrgUiStyleForOrgVariables>;

export function useUpsertMyUiStylePreference(options?: useDataConnectMutationOptions<UpsertMyUiStylePreferenceData, FirebaseError, UpsertMyUiStylePreferenceVariables>): UseDataConnectMutationResult<UpsertMyUiStylePreferenceData, UpsertMyUiStylePreferenceVariables>;
export function useUpsertMyUiStylePreference(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertMyUiStylePreferenceData, FirebaseError, UpsertMyUiStylePreferenceVariables>): UseDataConnectMutationResult<UpsertMyUiStylePreferenceData, UpsertMyUiStylePreferenceVariables>;

export function useDeleteMyUiStylePreference(options?: useDataConnectMutationOptions<DeleteMyUiStylePreferenceData, FirebaseError, DeleteMyUiStylePreferenceVariables>): UseDataConnectMutationResult<DeleteMyUiStylePreferenceData, DeleteMyUiStylePreferenceVariables>;
export function useDeleteMyUiStylePreference(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteMyUiStylePreferenceData, FirebaseError, DeleteMyUiStylePreferenceVariables>): UseDataConnectMutationResult<DeleteMyUiStylePreferenceData, DeleteMyUiStylePreferenceVariables>;

export function useUpsertUserUiStylePreferenceForOrg(options?: useDataConnectMutationOptions<UpsertUserUiStylePreferenceForOrgData, FirebaseError, UpsertUserUiStylePreferenceForOrgVariables>): UseDataConnectMutationResult<UpsertUserUiStylePreferenceForOrgData, UpsertUserUiStylePreferenceForOrgVariables>;
export function useUpsertUserUiStylePreferenceForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertUserUiStylePreferenceForOrgData, FirebaseError, UpsertUserUiStylePreferenceForOrgVariables>): UseDataConnectMutationResult<UpsertUserUiStylePreferenceForOrgData, UpsertUserUiStylePreferenceForOrgVariables>;

export function useDeleteUserUiStylePreferenceForOrg(options?: useDataConnectMutationOptions<DeleteUserUiStylePreferenceForOrgData, FirebaseError, DeleteUserUiStylePreferenceForOrgVariables>): UseDataConnectMutationResult<DeleteUserUiStylePreferenceForOrgData, DeleteUserUiStylePreferenceForOrgVariables>;
export function useDeleteUserUiStylePreferenceForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteUserUiStylePreferenceForOrgData, FirebaseError, DeleteUserUiStylePreferenceForOrgVariables>): UseDataConnectMutationResult<DeleteUserUiStylePreferenceForOrgData, DeleteUserUiStylePreferenceForOrgVariables>;

export function useInsertClientForOrg(options?: useDataConnectMutationOptions<InsertClientForOrgData, FirebaseError, InsertClientForOrgVariables>): UseDataConnectMutationResult<InsertClientForOrgData, InsertClientForOrgVariables>;
export function useInsertClientForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertClientForOrgData, FirebaseError, InsertClientForOrgVariables>): UseDataConnectMutationResult<InsertClientForOrgData, InsertClientForOrgVariables>;

export function useUpdateClientForOrg(options?: useDataConnectMutationOptions<UpdateClientForOrgData, FirebaseError, UpdateClientForOrgVariables>): UseDataConnectMutationResult<UpdateClientForOrgData, UpdateClientForOrgVariables>;
export function useUpdateClientForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientForOrgData, FirebaseError, UpdateClientForOrgVariables>): UseDataConnectMutationResult<UpdateClientForOrgData, UpdateClientForOrgVariables>;

export function useDeleteClientForOrg(options?: useDataConnectMutationOptions<DeleteClientForOrgData, FirebaseError, DeleteClientForOrgVariables>): UseDataConnectMutationResult<DeleteClientForOrgData, DeleteClientForOrgVariables>;
export function useDeleteClientForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteClientForOrgData, FirebaseError, DeleteClientForOrgVariables>): UseDataConnectMutationResult<DeleteClientForOrgData, DeleteClientForOrgVariables>;

export function useInsertIndividualJobForOrg(options?: useDataConnectMutationOptions<InsertIndividualJobForOrgData, FirebaseError, InsertIndividualJobForOrgVariables>): UseDataConnectMutationResult<InsertIndividualJobForOrgData, InsertIndividualJobForOrgVariables>;
export function useInsertIndividualJobForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertIndividualJobForOrgData, FirebaseError, InsertIndividualJobForOrgVariables>): UseDataConnectMutationResult<InsertIndividualJobForOrgData, InsertIndividualJobForOrgVariables>;

export function useUpdateIndividualJobForOrg(options?: useDataConnectMutationOptions<UpdateIndividualJobForOrgData, FirebaseError, UpdateIndividualJobForOrgVariables>): UseDataConnectMutationResult<UpdateIndividualJobForOrgData, UpdateIndividualJobForOrgVariables>;
export function useUpdateIndividualJobForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateIndividualJobForOrgData, FirebaseError, UpdateIndividualJobForOrgVariables>): UseDataConnectMutationResult<UpdateIndividualJobForOrgData, UpdateIndividualJobForOrgVariables>;

export function useDeleteIndividualJobForOrg(options?: useDataConnectMutationOptions<DeleteIndividualJobForOrgData, FirebaseError, DeleteIndividualJobForOrgVariables>): UseDataConnectMutationResult<DeleteIndividualJobForOrgData, DeleteIndividualJobForOrgVariables>;
export function useDeleteIndividualJobForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteIndividualJobForOrgData, FirebaseError, DeleteIndividualJobForOrgVariables>): UseDataConnectMutationResult<DeleteIndividualJobForOrgData, DeleteIndividualJobForOrgVariables>;

export function useUpsertTaskForOrg(options?: useDataConnectMutationOptions<UpsertTaskForOrgData, FirebaseError, UpsertTaskForOrgVariables>): UseDataConnectMutationResult<UpsertTaskForOrgData, UpsertTaskForOrgVariables>;
export function useUpsertTaskForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertTaskForOrgData, FirebaseError, UpsertTaskForOrgVariables>): UseDataConnectMutationResult<UpsertTaskForOrgData, UpsertTaskForOrgVariables>;

export function useDeleteTaskForOrg(options?: useDataConnectMutationOptions<DeleteTaskForOrgData, FirebaseError, DeleteTaskForOrgVariables>): UseDataConnectMutationResult<DeleteTaskForOrgData, DeleteTaskForOrgVariables>;
export function useDeleteTaskForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTaskForOrgData, FirebaseError, DeleteTaskForOrgVariables>): UseDataConnectMutationResult<DeleteTaskForOrgData, DeleteTaskForOrgVariables>;

export function useInsertZoneForOrg(options?: useDataConnectMutationOptions<InsertZoneForOrgData, FirebaseError, InsertZoneForOrgVariables>): UseDataConnectMutationResult<InsertZoneForOrgData, InsertZoneForOrgVariables>;
export function useInsertZoneForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertZoneForOrgData, FirebaseError, InsertZoneForOrgVariables>): UseDataConnectMutationResult<InsertZoneForOrgData, InsertZoneForOrgVariables>;

export function useUpdateZoneForOrg(options?: useDataConnectMutationOptions<UpdateZoneForOrgData, FirebaseError, UpdateZoneForOrgVariables>): UseDataConnectMutationResult<UpdateZoneForOrgData, UpdateZoneForOrgVariables>;
export function useUpdateZoneForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateZoneForOrgData, FirebaseError, UpdateZoneForOrgVariables>): UseDataConnectMutationResult<UpdateZoneForOrgData, UpdateZoneForOrgVariables>;

export function useDeleteZoneForOrg(options?: useDataConnectMutationOptions<DeleteZoneForOrgData, FirebaseError, DeleteZoneForOrgVariables>): UseDataConnectMutationResult<DeleteZoneForOrgData, DeleteZoneForOrgVariables>;
export function useDeleteZoneForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteZoneForOrgData, FirebaseError, DeleteZoneForOrgVariables>): UseDataConnectMutationResult<DeleteZoneForOrgData, DeleteZoneForOrgVariables>;

export function useInsertWorkdayForOrg(options?: useDataConnectMutationOptions<InsertWorkdayForOrgData, FirebaseError, InsertWorkdayForOrgVariables>): UseDataConnectMutationResult<InsertWorkdayForOrgData, InsertWorkdayForOrgVariables>;
export function useInsertWorkdayForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertWorkdayForOrgData, FirebaseError, InsertWorkdayForOrgVariables>): UseDataConnectMutationResult<InsertWorkdayForOrgData, InsertWorkdayForOrgVariables>;

export function useUpdateWorkdayForOrg(options?: useDataConnectMutationOptions<UpdateWorkdayForOrgData, FirebaseError, UpdateWorkdayForOrgVariables>): UseDataConnectMutationResult<UpdateWorkdayForOrgData, UpdateWorkdayForOrgVariables>;
export function useUpdateWorkdayForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateWorkdayForOrgData, FirebaseError, UpdateWorkdayForOrgVariables>): UseDataConnectMutationResult<UpdateWorkdayForOrgData, UpdateWorkdayForOrgVariables>;

export function useDeleteWorkdayForOrg(options?: useDataConnectMutationOptions<DeleteWorkdayForOrgData, FirebaseError, DeleteWorkdayForOrgVariables>): UseDataConnectMutationResult<DeleteWorkdayForOrgData, DeleteWorkdayForOrgVariables>;
export function useDeleteWorkdayForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteWorkdayForOrgData, FirebaseError, DeleteWorkdayForOrgVariables>): UseDataConnectMutationResult<DeleteWorkdayForOrgData, DeleteWorkdayForOrgVariables>;

export function useInsertEventForOrg(options?: useDataConnectMutationOptions<InsertEventForOrgData, FirebaseError, InsertEventForOrgVariables>): UseDataConnectMutationResult<InsertEventForOrgData, InsertEventForOrgVariables>;
export function useInsertEventForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertEventForOrgData, FirebaseError, InsertEventForOrgVariables>): UseDataConnectMutationResult<InsertEventForOrgData, InsertEventForOrgVariables>;

export function useUpdateEventForOrg(options?: useDataConnectMutationOptions<UpdateEventForOrgData, FirebaseError, UpdateEventForOrgVariables>): UseDataConnectMutationResult<UpdateEventForOrgData, UpdateEventForOrgVariables>;
export function useUpdateEventForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEventForOrgData, FirebaseError, UpdateEventForOrgVariables>): UseDataConnectMutationResult<UpdateEventForOrgData, UpdateEventForOrgVariables>;

export function useDeleteEventForOrg(options?: useDataConnectMutationOptions<DeleteEventForOrgData, FirebaseError, DeleteEventForOrgVariables>): UseDataConnectMutationResult<DeleteEventForOrgData, DeleteEventForOrgVariables>;
export function useDeleteEventForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteEventForOrgData, FirebaseError, DeleteEventForOrgVariables>): UseDataConnectMutationResult<DeleteEventForOrgData, DeleteEventForOrgVariables>;

export function useInsertBackupCycleForOrg(options?: useDataConnectMutationOptions<InsertBackupCycleForOrgData, FirebaseError, InsertBackupCycleForOrgVariables>): UseDataConnectMutationResult<InsertBackupCycleForOrgData, InsertBackupCycleForOrgVariables>;
export function useInsertBackupCycleForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertBackupCycleForOrgData, FirebaseError, InsertBackupCycleForOrgVariables>): UseDataConnectMutationResult<InsertBackupCycleForOrgData, InsertBackupCycleForOrgVariables>;

export function useUpdateBackupCycleForOrg(options?: useDataConnectMutationOptions<UpdateBackupCycleForOrgData, FirebaseError, UpdateBackupCycleForOrgVariables>): UseDataConnectMutationResult<UpdateBackupCycleForOrgData, UpdateBackupCycleForOrgVariables>;
export function useUpdateBackupCycleForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateBackupCycleForOrgData, FirebaseError, UpdateBackupCycleForOrgVariables>): UseDataConnectMutationResult<UpdateBackupCycleForOrgData, UpdateBackupCycleForOrgVariables>;

export function useInsertStorageForOrg(options?: useDataConnectMutationOptions<InsertStorageForOrgData, FirebaseError, InsertStorageForOrgVariables>): UseDataConnectMutationResult<InsertStorageForOrgData, InsertStorageForOrgVariables>;
export function useInsertStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertStorageForOrgData, FirebaseError, InsertStorageForOrgVariables>): UseDataConnectMutationResult<InsertStorageForOrgData, InsertStorageForOrgVariables>;

export function useUpdateStorageForOrg(options?: useDataConnectMutationOptions<UpdateStorageForOrgData, FirebaseError, UpdateStorageForOrgVariables>): UseDataConnectMutationResult<UpdateStorageForOrgData, UpdateStorageForOrgVariables>;
export function useUpdateStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateStorageForOrgData, FirebaseError, UpdateStorageForOrgVariables>): UseDataConnectMutationResult<UpdateStorageForOrgData, UpdateStorageForOrgVariables>;

export function useDeleteStorageForOrg(options?: useDataConnectMutationOptions<DeleteStorageForOrgData, FirebaseError, DeleteStorageForOrgVariables>): UseDataConnectMutationResult<DeleteStorageForOrgData, DeleteStorageForOrgVariables>;
export function useDeleteStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteStorageForOrgData, FirebaseError, DeleteStorageForOrgVariables>): UseDataConnectMutationResult<DeleteStorageForOrgData, DeleteStorageForOrgVariables>;

export function useInsertClientStorageForOrg(options?: useDataConnectMutationOptions<InsertClientStorageForOrgData, FirebaseError, InsertClientStorageForOrgVariables>): UseDataConnectMutationResult<InsertClientStorageForOrgData, InsertClientStorageForOrgVariables>;
export function useInsertClientStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<InsertClientStorageForOrgData, FirebaseError, InsertClientStorageForOrgVariables>): UseDataConnectMutationResult<InsertClientStorageForOrgData, InsertClientStorageForOrgVariables>;

export function useUpdateClientStorageForOrg(options?: useDataConnectMutationOptions<UpdateClientStorageForOrgData, FirebaseError, UpdateClientStorageForOrgVariables>): UseDataConnectMutationResult<UpdateClientStorageForOrgData, UpdateClientStorageForOrgVariables>;
export function useUpdateClientStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientStorageForOrgData, FirebaseError, UpdateClientStorageForOrgVariables>): UseDataConnectMutationResult<UpdateClientStorageForOrgData, UpdateClientStorageForOrgVariables>;

export function useDeleteClientStorageForOrg(options?: useDataConnectMutationOptions<DeleteClientStorageForOrgData, FirebaseError, DeleteClientStorageForOrgVariables>): UseDataConnectMutationResult<DeleteClientStorageForOrgData, DeleteClientStorageForOrgVariables>;
export function useDeleteClientStorageForOrg(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteClientStorageForOrgData, FirebaseError, DeleteClientStorageForOrgVariables>): UseDataConnectMutationResult<DeleteClientStorageForOrgData, DeleteClientStorageForOrgVariables>;

export function useStartWorkdayPause(options?: useDataConnectMutationOptions<StartWorkdayPauseData, FirebaseError, StartWorkdayPauseVariables>): UseDataConnectMutationResult<StartWorkdayPauseData, StartWorkdayPauseVariables>;
export function useStartWorkdayPause(dc: DataConnect, options?: useDataConnectMutationOptions<StartWorkdayPauseData, FirebaseError, StartWorkdayPauseVariables>): UseDataConnectMutationResult<StartWorkdayPauseData, StartWorkdayPauseVariables>;

export function useStopWorkdayPause(options?: useDataConnectMutationOptions<StopWorkdayPauseData, FirebaseError, StopWorkdayPauseVariables>): UseDataConnectMutationResult<StopWorkdayPauseData, StopWorkdayPauseVariables>;
export function useStopWorkdayPause(dc: DataConnect, options?: useDataConnectMutationOptions<StopWorkdayPauseData, FirebaseError, StopWorkdayPauseVariables>): UseDataConnectMutationResult<StopWorkdayPauseData, StopWorkdayPauseVariables>;

export function useMyOrganizations(options?: useDataConnectQueryOptions<MyOrganizationsData>): UseDataConnectQueryResult<MyOrganizationsData, undefined>;
export function useMyOrganizations(dc: DataConnect, options?: useDataConnectQueryOptions<MyOrganizationsData>): UseDataConnectQueryResult<MyOrganizationsData, undefined>;

export function useOrgUiStyleForOrg(vars: OrgUiStyleForOrgVariables, options?: useDataConnectQueryOptions<OrgUiStyleForOrgData>): UseDataConnectQueryResult<OrgUiStyleForOrgData, OrgUiStyleForOrgVariables>;
export function useOrgUiStyleForOrg(dc: DataConnect, vars: OrgUiStyleForOrgVariables, options?: useDataConnectQueryOptions<OrgUiStyleForOrgData>): UseDataConnectQueryResult<OrgUiStyleForOrgData, OrgUiStyleForOrgVariables>;

export function useMyUiStylePreference(vars: MyUiStylePreferenceVariables, options?: useDataConnectQueryOptions<MyUiStylePreferenceData>): UseDataConnectQueryResult<MyUiStylePreferenceData, MyUiStylePreferenceVariables>;
export function useMyUiStylePreference(dc: DataConnect, vars: MyUiStylePreferenceVariables, options?: useDataConnectQueryOptions<MyUiStylePreferenceData>): UseDataConnectQueryResult<MyUiStylePreferenceData, MyUiStylePreferenceVariables>;

export function useUserUiStylePreferencesForOrg(vars: UserUiStylePreferencesForOrgVariables, options?: useDataConnectQueryOptions<UserUiStylePreferencesForOrgData>): UseDataConnectQueryResult<UserUiStylePreferencesForOrgData, UserUiStylePreferencesForOrgVariables>;
export function useUserUiStylePreferencesForOrg(dc: DataConnect, vars: UserUiStylePreferencesForOrgVariables, options?: useDataConnectQueryOptions<UserUiStylePreferencesForOrgData>): UseDataConnectQueryResult<UserUiStylePreferencesForOrgData, UserUiStylePreferencesForOrgVariables>;

export function useCanManageWorkersForOrg(vars: CanManageWorkersForOrgVariables, options?: useDataConnectQueryOptions<CanManageWorkersForOrgData>): UseDataConnectQueryResult<CanManageWorkersForOrgData, CanManageWorkersForOrgVariables>;
export function useCanManageWorkersForOrg(dc: DataConnect, vars: CanManageWorkersForOrgVariables, options?: useDataConnectQueryOptions<CanManageWorkersForOrgData>): UseDataConnectQueryResult<CanManageWorkersForOrgData, CanManageWorkersForOrgVariables>;

export function useWorkersForOrg(vars: WorkersForOrgVariables, options?: useDataConnectQueryOptions<WorkersForOrgData>): UseDataConnectQueryResult<WorkersForOrgData, WorkersForOrgVariables>;
export function useWorkersForOrg(dc: DataConnect, vars: WorkersForOrgVariables, options?: useDataConnectQueryOptions<WorkersForOrgData>): UseDataConnectQueryResult<WorkersForOrgData, WorkersForOrgVariables>;

export function useAdminWorkerCredentialForOrg(vars: AdminWorkerCredentialForOrgVariables, options?: useDataConnectQueryOptions<AdminWorkerCredentialForOrgData>): UseDataConnectQueryResult<AdminWorkerCredentialForOrgData, AdminWorkerCredentialForOrgVariables>;
export function useAdminWorkerCredentialForOrg(dc: DataConnect, vars: AdminWorkerCredentialForOrgVariables, options?: useDataConnectQueryOptions<AdminWorkerCredentialForOrgData>): UseDataConnectQueryResult<AdminWorkerCredentialForOrgData, AdminWorkerCredentialForOrgVariables>;

export function useClientsForOrg(vars: ClientsForOrgVariables, options?: useDataConnectQueryOptions<ClientsForOrgData>): UseDataConnectQueryResult<ClientsForOrgData, ClientsForOrgVariables>;
export function useClientsForOrg(dc: DataConnect, vars: ClientsForOrgVariables, options?: useDataConnectQueryOptions<ClientsForOrgData>): UseDataConnectQueryResult<ClientsForOrgData, ClientsForOrgVariables>;

export function useIndividualJobsForOrg(vars: IndividualJobsForOrgVariables, options?: useDataConnectQueryOptions<IndividualJobsForOrgData>): UseDataConnectQueryResult<IndividualJobsForOrgData, IndividualJobsForOrgVariables>;
export function useIndividualJobsForOrg(dc: DataConnect, vars: IndividualJobsForOrgVariables, options?: useDataConnectQueryOptions<IndividualJobsForOrgData>): UseDataConnectQueryResult<IndividualJobsForOrgData, IndividualJobsForOrgVariables>;

export function useTasksForOrg(vars: TasksForOrgVariables, options?: useDataConnectQueryOptions<TasksForOrgData>): UseDataConnectQueryResult<TasksForOrgData, TasksForOrgVariables>;
export function useTasksForOrg(dc: DataConnect, vars: TasksForOrgVariables, options?: useDataConnectQueryOptions<TasksForOrgData>): UseDataConnectQueryResult<TasksForOrgData, TasksForOrgVariables>;

export function useZonesForOrg(vars: ZonesForOrgVariables, options?: useDataConnectQueryOptions<ZonesForOrgData>): UseDataConnectQueryResult<ZonesForOrgData, ZonesForOrgVariables>;
export function useZonesForOrg(dc: DataConnect, vars: ZonesForOrgVariables, options?: useDataConnectQueryOptions<ZonesForOrgData>): UseDataConnectQueryResult<ZonesForOrgData, ZonesForOrgVariables>;

export function useWorkdaysForOrg(vars: WorkdaysForOrgVariables, options?: useDataConnectQueryOptions<WorkdaysForOrgData>): UseDataConnectQueryResult<WorkdaysForOrgData, WorkdaysForOrgVariables>;
export function useWorkdaysForOrg(dc: DataConnect, vars: WorkdaysForOrgVariables, options?: useDataConnectQueryOptions<WorkdaysForOrgData>): UseDataConnectQueryResult<WorkdaysForOrgData, WorkdaysForOrgVariables>;

export function useBackupCyclesForOrg(vars: BackupCyclesForOrgVariables, options?: useDataConnectQueryOptions<BackupCyclesForOrgData>): UseDataConnectQueryResult<BackupCyclesForOrgData, BackupCyclesForOrgVariables>;
export function useBackupCyclesForOrg(dc: DataConnect, vars: BackupCyclesForOrgVariables, options?: useDataConnectQueryOptions<BackupCyclesForOrgData>): UseDataConnectQueryResult<BackupCyclesForOrgData, BackupCyclesForOrgVariables>;

export function useEventsForOrg(vars: EventsForOrgVariables, options?: useDataConnectQueryOptions<EventsForOrgData>): UseDataConnectQueryResult<EventsForOrgData, EventsForOrgVariables>;
export function useEventsForOrg(dc: DataConnect, vars: EventsForOrgVariables, options?: useDataConnectQueryOptions<EventsForOrgData>): UseDataConnectQueryResult<EventsForOrgData, EventsForOrgVariables>;

export function useWorkerWorkdaysForOrg(vars: WorkerWorkdaysForOrgVariables, options?: useDataConnectQueryOptions<WorkerWorkdaysForOrgData>): UseDataConnectQueryResult<WorkerWorkdaysForOrgData, WorkerWorkdaysForOrgVariables>;
export function useWorkerWorkdaysForOrg(dc: DataConnect, vars: WorkerWorkdaysForOrgVariables, options?: useDataConnectQueryOptions<WorkerWorkdaysForOrgData>): UseDataConnectQueryResult<WorkerWorkdaysForOrgData, WorkerWorkdaysForOrgVariables>;

export function useStorageForOrg(vars: StorageForOrgVariables, options?: useDataConnectQueryOptions<StorageForOrgData>): UseDataConnectQueryResult<StorageForOrgData, StorageForOrgVariables>;
export function useStorageForOrg(dc: DataConnect, vars: StorageForOrgVariables, options?: useDataConnectQueryOptions<StorageForOrgData>): UseDataConnectQueryResult<StorageForOrgData, StorageForOrgVariables>;

export function useClientStorageForClient(vars: ClientStorageForClientVariables, options?: useDataConnectQueryOptions<ClientStorageForClientData>): UseDataConnectQueryResult<ClientStorageForClientData, ClientStorageForClientVariables>;
export function useClientStorageForClient(dc: DataConnect, vars: ClientStorageForClientVariables, options?: useDataConnectQueryOptions<ClientStorageForClientData>): UseDataConnectQueryResult<ClientStorageForClientData, ClientStorageForClientVariables>;

export function useClientStorageForOrg(vars: ClientStorageForOrgVariables, options?: useDataConnectQueryOptions<ClientStorageForOrgData>): UseDataConnectQueryResult<ClientStorageForOrgData, ClientStorageForOrgVariables>;
export function useClientStorageForOrg(dc: DataConnect, vars: ClientStorageForOrgVariables, options?: useDataConnectQueryOptions<ClientStorageForOrgData>): UseDataConnectQueryResult<ClientStorageForOrgData, ClientStorageForOrgVariables>;

export function useWorkdayPausesForOrg(vars: WorkdayPausesForOrgVariables, options?: useDataConnectQueryOptions<WorkdayPausesForOrgData>): UseDataConnectQueryResult<WorkdayPausesForOrgData, WorkdayPausesForOrgVariables>;
export function useWorkdayPausesForOrg(dc: DataConnect, vars: WorkdayPausesForOrgVariables, options?: useDataConnectQueryOptions<WorkdayPausesForOrgData>): UseDataConnectQueryResult<WorkdayPausesForOrgData, WorkdayPausesForOrgVariables>;

export function useActiveWorkdayPauseForWorker(vars: ActiveWorkdayPauseForWorkerVariables, options?: useDataConnectQueryOptions<ActiveWorkdayPauseForWorkerData>): UseDataConnectQueryResult<ActiveWorkdayPauseForWorkerData, ActiveWorkdayPauseForWorkerVariables>;
export function useActiveWorkdayPauseForWorker(dc: DataConnect, vars: ActiveWorkdayPauseForWorkerVariables, options?: useDataConnectQueryOptions<ActiveWorkdayPauseForWorkerData>): UseDataConnectQueryResult<ActiveWorkdayPauseForWorkerData, ActiveWorkdayPauseForWorkerVariables>;
